### ISSUE TITLE
(Question) Excavators and so on?

### ISSUE THREAD

**Issue by Revemohl** [VapourDrive/Hammerz#3]
Just out of curiosity, do you plan to implement excavators, lumber axes and scythes as well?

**Comment by ColinGBos** [comment]
To tell you the honest truth I'm not sure. I might. The thing is that there are already more mods out there that add scythes. Example: Thermal Foundation adds them for all of it's toolsets (so then chances are most people would have multiples of many scythes). I like the simplicity of just having hammers so I may end up making a sibling mod that adds the others and have it be dependent on this one, so that I won't feel bad for throwing things in there, and then I'll for sure add Excavators, Scythes and Lumberaxes.
