### ISSUE TITLE
Crazy TC5 hammer aspects

### ISSUE THREAD

**Issue by OnmyojiOmn** [VapourDrive/Hammerz#9]
All hammers have, regardless of material:

26 Vitreus
22 Desiderium
15 Ignis
12 Metallum
7 Sensus
5 Instrumentum

Looks like the values for gold hammers might have been copy/pasted, and TC4 aspects converted to TC5 with strange results.

**Comment by ColinGBos** [comment]
I never actually attributed any aspects to any of the hammers, I have a feeling Thaumcraft builds an aspect list if none are registered based on various recipes you include, such as infusion crafting for the Hammer of the Core and the void metal/thaumium hammers and whatever else. Since the hammers technically share a single item it means they all get attributed the same aspect list. I'm not really sure however and can't really scope it out because Thaumcraft isn't open source. I will have a look at what the API offers for registering aspects for the hammers myself so they aren't so random.
